name: Build and test

on:
  push:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish ${{env.PROJECT-PATH}} -c Release -o ${{env.DOTNET_ROOT}}/Alamb-clock-api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          if: ${{ github.ref_name }} == 'main'
          path: ${{env.DOTNET_ROOT}}/Alamb-clock-api

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'Alamb-clock-api'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDE8C09DF462494682D8A5C60BF206CD }}
  #         package: .