name: API - Build and test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
    branches:
      - 'main'

env:
  project-path: ./src/Host

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build $project-path --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
